### ISSUE TITLE
Include mosquitto-clients

### ISSUE THREAD

**Issue by libre-7** [cmccambridge/mosquitto-unraid#2]
Does this docker include mosquitto-clients? 
 ```
# mosquitto_pub -h localhost -t "test" -m "hello world"
sh: mosquitto_pub: not found
```
If mosquitto-clients was not included was there a reason for this or was it an oversight? Thanks for the updated mosquitto version. Using on UnRaid.

**Comment by cmccambridge** [comment]
I will check into this.

**Comment by cmccambridge** [comment]
Confirmed that the clients are not currently a part of this container image. This image is (so far) a very minimal addition on top of the official Eclipse Mosquitto docker images that just adds some tweaks to be more user-friendly in unraid, so the image defaulted to "whatever the official image does."

I can see the clients being useful for usability in unraid, though... I'll investigate what it would require to add them.

**Comment by libre-7** [comment]
thanks

**Comment by cmccambridge** [comment]
@w111a On the latest version of mosquitto-unraid (currently 1.6.2), the `mosquitto_sub` and `mosquitto_pub` clients are now included in the container image. Please update your container using the latest Docker Hub images (`docker pull cmccambridge/mosquitto-unraid`). 

Let me know if you encounter any issues!

(P.S. if you're still affected by #1 , please see the comments there on how to ensure that your unraid container is up to date and pointing at the Docker Hub repository going forward.)
