### ISSUE TITLE
Suggestion: Link hub.docker.com to your github

### ISSUE THREAD

**Issue by ElectricImpossible** [cmccambridge/mosquitto-unraid#21]
I appreciate your work with this simple concise container. Thanks!

Could I suggest you have a link to your gibhub repo via your hub,docker.com page, helps when you publish updates and we can see what they contain.

:)

**Comment by cmccambridge** [comment]
Great suggestion, thank you. Done!

**Comment by cmccambridge** [comment]
https://hub.docker.com/r/cmccambridge/mosquitto-unraid
